name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mbrzoska/biopython
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: mbrzoska
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      - name: Push image to docker hub 
        run: docker push mbrzoska/biopython:latest

  execute-tests:
    runs-on: ubuntu-latest
    container:
          image: docker://mbrzoska/biopython:latest
          credentials:
              username: mbrzoska
              password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
      - name: Clone code
        shell: bash
        run: |
          git clone https://github.com/brzoskx/biopython_mfork.git
      - name: Build biopython
        shell: bash
        run: | 
          cd biopython_mfork && python3.9 setup.py build
      - name: Run tests
        shell: bash
        run: | 
           cd biopython_mfork && python3.9 setup.py test --offline
     